name: first demo workflow

on:
  push:
    branches:
      - main

jobs:
  buildjob1:
    runs-on: ubuntu-latest
    # Whatever mentioned under steps will be performed sequentially
    steps:
      - name: step1
        uses: actions/checkout@v4